MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.10"                # [osx and x86_64]
# hmaarrfk -- not sure why, we got a static_assert undefined error
# but it seems to be defined at the line where the error points to
# in #include <assert.h>
# https://github.com/util-linux/util-linux/blob/v2.39.3/include/xxhash.h#L1556
c_compiler_version:        # [osx]
  - 15                     # [osx]
cxx_compiler_version:      # [osx]
  - 15                     # [osx]
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
docker_image:                                     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                         # [linux64]
  - cos7                                          # [linux64]
